# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Representation": "00_representation.ipynb",
         "Node": "00_representation.ipynb",
         "nn.Module.to_representation": "00_representation.ipynb",
         "Learner.to_representation": "00_representation.ipynb",
         "Node.get_dict": "00_representation.ipynb",
         "Representation.to_json": "00_representation.ipynb",
         "logger": "01_explorer.ipynb",
         "Events": "01_explorer.ipynb",
         "clientEvents": "01_explorer.ipynb",
         "serverEvents": "01_explorer.ipynb",
         "FastExplorer": "01_explorer.ipynb",
         "load_input": "01_explorer.ipynb",
         "Learner.fastexplorer": "01_explorer.ipynb"}

modules = ["representation.py",
           "explorer.py"]

doc_url = "https://renato145.github.io/fastexplorer/"

git_url = "https://github.com/renato145/fastexplorer/tree/master/"

def custom_doc_links(name): return None
